# Generated by Django 3.2 on 2022-12-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.EmailField(default='', max_length=100, primary_key=True, serialize=False)),
                ('email', models.EmailField(default='', max_length=100, verbose_name='email')),
                ('password', models.CharField(default='', max_length=300)),
                ('phone', models.CharField(default='', max_length=25)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
