# Generated by Django 3.2 on 2022-12-19 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0004_auto_20221219_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='email',
            field=models.EmailField(default='', max_length=100, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='phone',
            field=models.CharField(default='', max_length=25),
        ),
    ]
