# Generated by Django 3.2 on 2022-12-15 07:24

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0004_owner_last_login'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='owner',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
