# Generated by Django 3.2 on 2022-12-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0004_owner_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='username',
            field=models.CharField(default='', max_length=30),
        ),
    ]
