# Generated by Django 3.2 on 2022-12-15 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0005_alter_owner_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='owner',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='owner',
            name='username',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
    ]
