# Generated by Django 3.2 on 2022-12-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0006_auto_20221215_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='username',
            field=models.CharField(default='', max_length=30),
        ),
    ]
