# Generated by Django 3.2 on 2022-12-17 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0006_auto_20221217_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='is_staff',
        ),
    ]
