# Generated by Django 3.2 on 2022-12-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0007_remove_owner_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
