# Generated by Django 3.2 on 2022-12-17 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0008_owner_is_active'),
        ('owner', '0008_remove_owner_username'),
    ]

    operations = [
    ]
