# Generated by Django 3.2 on 2022-12-17 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0009_merge_0008_owner_is_active_0008_remove_owner_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='username',
        ),
    ]
