# Generated by Django 3.2 on 2022-12-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerSignUp', '0002_auto_20221206_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='', max_length=25),
        ),
    ]
