# Generated by Django 3.2 on 2022-12-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerSignUp', '0005_auto_20221207_0247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.EmailField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
