# Generated by Django 3.2 on 2022-12-07 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': '존재하는 카페명입니다'}, max_length=100, unique=True, verbose_name='카페명')),
                ('max_occupancy', models.IntegerField(null=True, verbose_name='최대수용인원')),
                ('address', models.CharField(max_length=100, null=True, verbose_name='주소')),
                ('datail_add', models.CharField(max_length=100, null=True, verbose_name='주소')),
                ('cafe_phone', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cafe_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cafe/', verbose_name='카페IMAGE')),
                ('cafe_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cafe.cafe')),
            ],
        ),
    ]
