# Generated by Django 3.2 on 2022-12-07 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ownerSignUp', '0001_initial'),
        ('cafe', '0002_auto_20221207_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cafe_image',
            old_name='cafe_id',
            new_name='cafe',
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='owner_id',
        ),
        migrations.AddField(
            model_name='cafe',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ownerSignUp.owner'),
        ),
    ]
