# Generated by Django 3.2 on 2022-12-20 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('cafe_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(error_messages={'unique': '존재하는 카페명입니다'}, max_length=100, unique=True, verbose_name='카페명')),
                ('max_occupancy', models.IntegerField(null=True, verbose_name='최대수용인원')),
                ('address', models.CharField(max_length=100, null=True, verbose_name='주소')),
                ('datail_add', models.CharField(max_length=100, null=True, verbose_name='상세주소')),
                ('cafe_phone', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'cafe',
            },
        ),
        migrations.CreateModel(
            name='Cafe_review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cafe_menu',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True, verbose_name='메뉴명')),
                ('price', models.CharField(max_length=100, null=True, verbose_name='가격')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cafeMenu/', verbose_name='메뉴IMAGE')),
                ('cafe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cafe.cafe')),
            ],
            options={
                'db_table': 'cafe_menu',
            },
        ),
        migrations.CreateModel(
            name='Cafe_image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cafe/', verbose_name='카페IMAGE')),
                ('cafe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cafe.cafe')),
            ],
            options={
                'db_table': 'cafe_image',
            },
        ),
    ]
