# Generated by Django 3.2 on 2022-12-31 07:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('cafe_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(error_messages={'unique': '존재하는 카페명입니다'}, max_length=100, unique=True, verbose_name='카페명')),
                ('max_occupancy', models.IntegerField(null=True, verbose_name='최대수용인원')),
                ('address', models.CharField(max_length=100, null=True, verbose_name='주소')),
                ('datail_add', models.CharField(max_length=100, null=True, verbose_name='상세주소')),
                ('cafe_phone', models.CharField(max_length=50, null=True)),
                ('like_users', models.ManyToManyField(blank=True, related_name='like_users', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cafe',
            },
        ),
        migrations.CreateModel(
            name='Cafe_wordcloud',
            fields=[
                ('word_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.ImageField(blank=True, null=True, upload_to='', verbose_name='price IMAGE')),
                ('drink', models.ImageField(blank=True, null=True, upload_to='', verbose_name='drink IMAGE')),
                ('dessert', models.ImageField(blank=True, null=True, upload_to='', verbose_name='dessert IMAGE')),
                ('service', models.ImageField(blank=True, null=True, upload_to='', verbose_name='service IMAGE')),
                ('customers', models.ImageField(blank=True, null=True, upload_to='', verbose_name='customers IMAGE')),
                ('interior', models.ImageField(blank=True, null=True, upload_to='', verbose_name='interior IMAGE')),
                ('view', models.ImageField(blank=True, null=True, upload_to='', verbose_name='view IMAGE')),
                ('parking', models.ImageField(blank=True, null=True, upload_to='', verbose_name='parking IMAGE')),
            ],
            options={
                'db_table': 'cafe_wordcloud',
            },
        ),
        migrations.CreateModel(
            name='Cafe_sentiment',
            fields=[
                ('sentiment_id', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='전체긍정비율')),
                ('total_count', models.IntegerField(null=True)),
                ('cafe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cafe.cafe')),
            ],
            options={
                'db_table': 'cafe_sentiment',
            },
        ),
        migrations.CreateModel(
            name='Cafe_review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False, verbose_name='리뷰id')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='리뷰제목')),
                ('score', models.IntegerField(default=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='별점')),
                ('content', models.TextField(verbose_name='리뷰내용')),
                ('deleted', models.BooleanField(default=False, verbose_name='삭제여부')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cafe/review/', verbose_name='리뷰IMAGE')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('cafe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cafe.cafe')),
                ('writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cafe_review',
            },
        ),
        migrations.CreateModel(
            name='Cafe_rank',
            fields=[
                ('rank_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100, null=True)),
                ('rank', models.IntegerField(null=True, verbose_name='순위')),
                ('ratio', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='카테고리별 긍정비율')),
                ('cnt', models.IntegerField(null=True)),
                ('positive_cnt', models.IntegerField(null=True)),
                ('sentiment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cafe.cafe_sentiment')),
            ],
            options={
                'db_table': 'cafe_rank',
            },
        ),
        migrations.CreateModel(
            name='Cafe_menu',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True, verbose_name='메뉴명')),
                ('price', models.CharField(max_length=100, null=True, verbose_name='가격')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cafe/menu/', verbose_name='메뉴IMAGE')),
                ('cafe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cafe.cafe')),
            ],
            options={
                'db_table': 'cafe_menu',
            },
        ),
        migrations.CreateModel(
            name='Cafe_keyword',
            fields=[
                ('keyword_id', models.AutoField(primary_key=True, serialize=False)),
                ('price_word', models.CharField(max_length=100, null=True)),
                ('price_count', models.IntegerField(default=0)),
                ('drink_word', models.CharField(max_length=100, null=True)),
                ('drink_count', models.IntegerField(default=0)),
                ('dessert_word', models.CharField(max_length=100, null=True)),
                ('dessert_count', models.IntegerField(default=0)),
                ('service_word', models.CharField(max_length=100, null=True)),
                ('service_count', models.IntegerField(default=0)),
                ('customers_word', models.CharField(max_length=100, null=True)),
                ('customers_count', models.IntegerField(null=True)),
                ('interior_word', models.CharField(max_length=100, null=True)),
                ('interior_count', models.IntegerField(null=True)),
                ('view_word', models.CharField(max_length=100, null=True)),
                ('view_count', models.IntegerField(null=True)),
                ('parking_word', models.CharField(max_length=100, null=True)),
                ('parking_count', models.IntegerField(null=True)),
                ('cafe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cafe.cafe')),
            ],
            options={
                'db_table': 'cafe_keyword',
            },
        ),
        migrations.CreateModel(
            name='Cafe_image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cafe/', verbose_name='카페IMAGE')),
                ('cafe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cafe.cafe')),
            ],
            options={
                'db_table': 'cafe_image',
            },
        ),
        migrations.CreateModel(
            name='Cafe_date',
            fields=[
                ('date_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=0)),
                ('cafe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cafe.cafe')),
            ],
            options={
                'db_table': 'cafe_date',
            },
        ),
        migrations.CreateModel(
            name='Cafe_congestion',
            fields=[
                ('congestion_id', models.AutoField(primary_key=True, serialize=False)),
                ('congestion', models.IntegerField(null=True)),
                ('cafe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cafe.cafe')),
            ],
            options={
                'db_table': 'cafe_congestion',
            },
        ),
        migrations.CreateModel(
            name='Cafe_comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='리뷰내용')),
                ('deleted', models.BooleanField(default=False, verbose_name='삭제여부')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cafe.cafe_review')),
                ('writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cafe_comment',
            },
        ),
    ]
