# Generated by Django 3.2 on 2022-12-22 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe_review',
            name='review_id2',
        ),
    ]
