# Generated by Django 3.2 on 2023-01-01 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_delete_cafe_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe_wordcloud',
            fields=[
                ('word_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.ImageField(blank=True, null=True, upload_to='', verbose_name='price IMAGE')),
                ('drink', models.ImageField(blank=True, null=True, upload_to='', verbose_name='drink IMAGE')),
                ('dessert', models.ImageField(blank=True, null=True, upload_to='', verbose_name='dessert IMAGE')),
                ('service', models.ImageField(blank=True, null=True, upload_to='', verbose_name='service IMAGE')),
                ('customers', models.ImageField(blank=True, null=True, upload_to='', verbose_name='customers IMAGE')),
                ('interior', models.ImageField(blank=True, null=True, upload_to='', verbose_name='interior IMAGE')),
                ('view', models.ImageField(blank=True, null=True, upload_to='', verbose_name='view IMAGE')),
                ('parking', models.ImageField(blank=True, null=True, upload_to='', verbose_name='parking IMAGE')),
                ('cafe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cafe.cafe')),
            ],
            options={
                'db_table': 'cafe_wordcloud',
            },
        ),
    ]
