# Generated by Django 3.2 on 2022-12-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_remove_cafe_cafe_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='cafe_phone',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
