# Generated by Django 3.2 on 2022-12-23 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_auto_20221223_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe_sentiment',
            fields=[
                ('sentiment_id', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='전체긍정비율')),
                ('price_rank', models.IntegerField()),
                ('price_sentiment', models.IntegerField()),
                ('drink_rank', models.IntegerField()),
                ('drink_sentiment', models.IntegerField()),
                ('dessert_rank', models.IntegerField()),
                ('dessert_sentiment', models.IntegerField()),
                ('service_rank', models.IntegerField()),
                ('service_sentiment', models.IntegerField()),
                ('customers_rank', models.IntegerField()),
                ('customers_sentiment', models.IntegerField()),
                ('interior_rank', models.IntegerField()),
                ('interior_sentiment', models.IntegerField()),
                ('view_rank', models.IntegerField()),
                ('view_sentiment', models.IntegerField()),
                ('parking_rank', models.IntegerField()),
                ('parking_sentiment', models.IntegerField()),
                ('trash_rank', models.IntegerField()),
                ('trash_sentiment', models.IntegerField()),
                ('cafe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cafe.cafe')),
            ],
            options={
                'db_table': 'cafe_sentiment',
            },
        ),
    ]
