# Generated by Django 3.2 on 2022-12-12 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_remove_owner_cafe'),
        ('cafe', '0003_cafe_cafe_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='owner.owner'),
        ),
    ]
