# Generated by Django 3.2 on 2022-12-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_cafe_sentiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe_sentiment',
            name='customers_sentiment',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cafe_sentiment',
            name='dessert_sentiment',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cafe_sentiment',
            name='drink_sentiment',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cafe_sentiment',
            name='interior_sentiment',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cafe_sentiment',
            name='parking_sentiment',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cafe_sentiment',
            name='price_sentiment',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cafe_sentiment',
            name='service_sentiment',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cafe_sentiment',
            name='trash_sentiment',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cafe_sentiment',
            name='view_sentiment',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
