# Generated by Django 3.2 on 2022-12-23 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0005_auto_20221223_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe_sentiment',
            name='trash_rank',
        ),
        migrations.RemoveField(
            model_name='cafe_sentiment',
            name='trash_sentiment',
        ),
        migrations.CreateModel(
            name='Cafe_keyword',
            fields=[
                ('keyword_id', models.AutoField(primary_key=True, serialize=False)),
                ('price_word', models.CharField(max_length=100, null=True)),
                ('price_count', models.IntegerField()),
                ('drink_word', models.CharField(max_length=100, null=True)),
                ('drink_count', models.IntegerField()),
                ('dessert_word', models.CharField(max_length=100, null=True)),
                ('dessert_count', models.IntegerField()),
                ('service_word', models.CharField(max_length=100, null=True)),
                ('service_count', models.IntegerField()),
                ('customers_word', models.CharField(max_length=100, null=True)),
                ('customers_count', models.IntegerField()),
                ('interior_word', models.CharField(max_length=100, null=True)),
                ('interior_count', models.IntegerField()),
                ('view_word', models.CharField(max_length=100, null=True)),
                ('view_count', models.IntegerField()),
                ('parking_word', models.CharField(max_length=100, null=True)),
                ('parking_count', models.IntegerField()),
                ('cafe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cafe.cafe')),
            ],
            options={
                'db_table': 'cafe_keyword',
            },
        ),
    ]
