# Generated by Django 3.2 on 2022-12-27 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cafe', '0006_auto_20221223_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe_congestion',
            fields=[
                ('favorites_id', models.AutoField(primary_key=True, serialize=False)),
                ('congestion', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'cafe_congestion',
            },
        ),
        migrations.AlterField(
            model_name='cafe_keyword',
            name='customers_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cafe_keyword',
            name='dessert_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cafe_keyword',
            name='drink_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cafe_keyword',
            name='interior_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cafe_keyword',
            name='parking_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cafe_keyword',
            name='price_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cafe_keyword',
            name='service_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cafe_keyword',
            name='view_count',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Cafe_favorites',
            fields=[
                ('favorites_id', models.AutoField(primary_key=True, serialize=False)),
                ('cafe', models.ManyToManyField(blank=True, related_name='cafe_list', to='cafe.Cafe')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cafe_favorites',
            },
        ),
    ]
