# Generated by Django 3.2 on 2023-01-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0006_auto_20230101_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe_menu',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='cafe/menu/', verbose_name='메뉴IMAGE'),
        ),
        migrations.AlterField(
            model_name='cafe_menu',
            name='price',
            field=models.IntegerField(null=True, verbose_name='가격'),
        ),
    ]
