# Generated by Django 3.2 on 2023-01-01 09:09

import cafe.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0006_auto_20230101_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe_wordcloud',
            name='customers',
            field=models.ImageField(blank=True, null=True, storage=cafe.models.OverwriteStorage(), upload_to='wordcloud/', verbose_name='customers IMAGE'),
        ),
        migrations.AlterField(
            model_name='cafe_wordcloud',
            name='dessert',
            field=models.ImageField(blank=True, null=True, storage=cafe.models.OverwriteStorage(), upload_to='wordcloud/', verbose_name='dessert IMAGE'),
        ),
        migrations.AlterField(
            model_name='cafe_wordcloud',
            name='drink',
            field=models.ImageField(blank=True, null=True, storage=cafe.models.OverwriteStorage(), upload_to='wordcloud/', verbose_name='drink IMAGE'),
        ),
        migrations.AlterField(
            model_name='cafe_wordcloud',
            name='interior',
            field=models.ImageField(blank=True, null=True, storage=cafe.models.OverwriteStorage(), upload_to='wordcloud/', verbose_name='interior IMAGE'),
        ),
        migrations.AlterField(
            model_name='cafe_wordcloud',
            name='parking',
            field=models.ImageField(blank=True, null=True, storage=cafe.models.OverwriteStorage(), upload_to='wordcloud/', verbose_name='parking IMAGE'),
        ),
        migrations.AlterField(
            model_name='cafe_wordcloud',
            name='price',
            field=models.ImageField(blank=True, null=True, upload_to='wordcloud/', verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='cafe_wordcloud',
            name='service',
            field=models.ImageField(blank=True, null=True, storage=cafe.models.OverwriteStorage(), upload_to='wordcloud/', verbose_name='service IMAGE'),
        ),
        migrations.AlterField(
            model_name='cafe_wordcloud',
            name='view',
            field=models.ImageField(blank=True, null=True, storage=cafe.models.OverwriteStorage(), upload_to='wordcloud/', verbose_name='view IMAGE'),
        ),
    ]
