# Generated by Django 3.2 on 2023-01-02 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0007_auto_20230101_1809'),
        ('cafe', '0007_auto_20230101_1817'),
    ]

    operations = [
    ]
