# Generated by Django 3.2 on 2022-12-28 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0007_auto_20221227_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe_sentiment',
            name='customers_rank',
        ),
        migrations.RemoveField(
            model_name='cafe_sentiment',
            name='customers_sentiment',
        ),
        migrations.RemoveField(
            model_name='cafe_sentiment',
            name='dessert_rank',
        ),
        migrations.RemoveField(
            model_name='cafe_sentiment',
            name='dessert_sentiment',
        ),
        migrations.RemoveField(
            model_name='cafe_sentiment',
            name='drink_rank',
        ),
        migrations.RemoveField(
            model_name='cafe_sentiment',
            name='drink_sentiment',
        ),
        migrations.RemoveField(
            model_name='cafe_sentiment',
            name='interior_rank',
        ),
        migrations.RemoveField(
            model_name='cafe_sentiment',
            name='interior_sentiment',
        ),
        migrations.RemoveField(
            model_name='cafe_sentiment',
            name='parking_rank',
        ),
        migrations.RemoveField(
            model_name='cafe_sentiment',
            name='parking_sentiment',
        ),
        migrations.RemoveField(
            model_name='cafe_sentiment',
            name='price_rank',
        ),
        migrations.RemoveField(
            model_name='cafe_sentiment',
            name='price_sentiment',
        ),
        migrations.RemoveField(
            model_name='cafe_sentiment',
            name='service_rank',
        ),
        migrations.RemoveField(
            model_name='cafe_sentiment',
            name='service_sentiment',
        ),
        migrations.RemoveField(
            model_name='cafe_sentiment',
            name='view_rank',
        ),
        migrations.RemoveField(
            model_name='cafe_sentiment',
            name='view_sentiment',
        ),
        migrations.CreateModel(
            name='Cafe_rank',
            fields=[
                ('rank_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100, null=True)),
                ('rank', models.IntegerField(null=True)),
                ('ratio', models.DecimalField(decimal_places=3, max_digits=5)),
                ('sentiment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cafe.cafe_sentiment')),
            ],
            options={
                'db_table': 'cafe_rank',
            },
        ),
    ]
