# Generated by Django 3.2 on 2023-01-02 03:15

import cafe.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0008_merge_0007_auto_20230101_1809_0007_auto_20230101_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe_wordcloud',
            name='price',
            field=models.ImageField(blank=True, null=True, storage=cafe.models.OverwriteStorage(), upload_to='wordcloud/', verbose_name='price'),
        ),
    ]
