# Generated by Django 3.2 on 2022-12-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0008_auto_20221228_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe_rank',
            name='rank',
            field=models.IntegerField(null=True, verbose_name='순위'),
        ),
        migrations.AlterField(
            model_name='cafe_rank',
            name='ratio',
            field=models.DecimalField(decimal_places=3, max_digits=5, verbose_name='카테고리별 긍정비율'),
        ),
    ]
