# Generated by Django 3.2 on 2022-12-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0009_auto_20221228_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe_rank',
            name='cnt',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cafe_rank',
            name='positive_cnt',
            field=models.IntegerField(null=True),
        ),
    ]
