# Generated by Django 3.2 on 2022-12-29 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0010_auto_20221229_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe_sentiment',
            name='total_count',
            field=models.IntegerField(null=True),
        ),
    ]
