# Generated by Django 3.2 on 2022-12-30 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0010_cafe_like_users'),
        ('cafe', '0011_cafe_sentiment_total_count'),
    ]

    operations = [
    ]
