# Generated by Django 3.2 on 2022-12-30 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0013_auto_20221230_1803'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cafe_favorites',
        ),
    ]
