# Generated by Django 3.2 on 2022-12-30 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0014_delete_cafe_favorites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cafe_congestion',
            old_name='favorites_id',
            new_name='congestion_id',
        ),
    ]
